[package]
name = "rosu-pp-js-v4-mania"
version = "2026.9.22-mania-surface.3"
edition = "2024"
license = "MIT"
description = "Public rosu-pp v4 bindings for osu!mania Rebirth and Sunny"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.77"
rosu-pp = { git = "https://github.com/ppy-sb/rosu-pp", rev = "3530ba72", features = ["sync"] }
wasm-bindgen = "0.2.100"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
strip = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--enable-bulk-memory", "--enable-nontrapping-float-to-int"]
